// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
///
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFxFwuUWZApxsnknxb6uV45P1d8zBM7Vc',
    appId: '1:274546699209:web:d792a7a4ea4dbe1a6a1618',
    messagingSenderId: '274546699209',
    projectId: 'ober-version-2',
    authDomain: 'ober-version-2.firebaseapp.com',
    storageBucket: 'ober-version-2.firebasestorage.app',
    measurementId: 'G-NL75PSQK2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHiMaCtVIvbDjatO-o0fWHVohdohkS__M',
    appId: '1:274546699209:android:638ded3edf42f57a6a1618',
    messagingSenderId: '274546699209',
    projectId: 'ober-version-2',
    storageBucket: 'ober-version-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBysTQk5GDCgMf7plwlWKK2eElaQUaZwIg',
    appId: '1:274546699209:ios:980725acf0ad61716a1618',
    messagingSenderId: '274546699209',
    projectId: 'ober-version-2',
    storageBucket: 'ober-version-2.firebasestorage.app',
    iosBundleId: 'com.example.oberVersion2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBysTQk5GDCgMf7plwlWKK2eElaQUaZwIg',
    appId: '1:274546699209:ios:980725acf0ad61716a1618',
    messagingSenderId: '274546699209',
    projectId: 'ober-version-2',
    storageBucket: 'ober-version-2.firebasestorage.app',
    iosBundleId: 'com.example.oberVersion2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFxFwuUWZApxsnknxb6uV45P1d8zBM7Vc',
    appId: '1:274546699209:web:da3f35476f27e2a36a1618',
    messagingSenderId: '274546699209',
    projectId: 'ober-version-2',
    authDomain: 'ober-version-2.firebaseapp.com',
    storageBucket: 'ober-version-2.firebasestorage.app',
    measurementId: 'G-5K5B554RHR',
  );
}
